"""Generate markdown reports from paper search results."""

from __future__ import annotations

import os
from collections import defaultdict
from datetime import datetime
from paper_search.arxiv_source import Paper

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "output")


def papers_to_markdown(papers: list[Paper], query: str) -> str:
    """Convert a list of papers into a well-structured markdown report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    today = datetime.now().strftime("%B %d, %Y")

    # Group papers by source
    by_source: dict[str, list[Paper]] = defaultdict(list)
    for p in papers:
        by_source[p.source].append(p)

    # Count venues from topics
    venues: dict[str, int] = defaultdict(int)
    for p in papers:
        if p.topics:
            for t in p.topics:
                venues[t] += 1

    lines = [
        f"# {query}",
        "",
        f"> **Last updated**: {now}  ",
        f"> **Date**: {today}  ",
        f"> **Total papers**: {len(papers)}  ",
    ]

    # Source breakdown
    source_parts = [f"{src} ({len(ps)})" for src, ps in sorted(by_source.items())]
    lines.append(f"> **Sources**: {' | '.join(source_parts)}  ")

    if venues:
        venue_parts = [f"{v} ({c})" for v, c in sorted(venues.items(), key=lambda x: -x[1])[:8]]
        lines.append(f"> **Venues**: {', '.join(venue_parts)}  ")

    lines.extend(["", "---", ""])

    # Table of contents
    lines.append("## Table of Contents")
    lines.append("")
    for src, ps in sorted(by_source.items()):
        lines.append(f"- [{src} ({len(ps)} papers)](#{''.join(src.lower().split())})")
    lines.extend(["", "---", ""])

    # Papers grouped by source, then sorted by date (newest first)
    idx = 1
    for src in sorted(by_source.keys()):
        src_papers = by_source[src]
        src_papers.sort(key=lambda p: p.published or datetime.min, reverse=True)

        lines.extend([
            f"## {src}",
            "",
            f"*{len(src_papers)} papers*",
            "",
        ])

        for paper in src_papers:
            authors_str = ", ".join(paper.authors[:5])
            if len(paper.authors) > 5:
                authors_str += f" et al. ({len(paper.authors)} total)"

            if paper.published:
                pub_date = paper.published.strftime("%B %Y")
            else:
                pub_date = "N/A"

            venue_tag = ""
            if paper.topics:
                venue_tag = f" `{paper.topics[0]}`"

            lines.extend([
                f"### {idx}. {paper.title}",
                "",
                f"| | |",
                f"|---|---|",
                f"| **Authors** | {authors_str} |",
                f"| **Published** | {pub_date}{venue_tag} |",
                f"| **Link** | [{paper.url}]({paper.url}) |",
            ])

            if paper.abstract:
                abstract = paper.abstract[:500]
                if len(paper.abstract) > 500:
                    abstract += "..."
                lines.extend([
                    "",
                    f"<details><summary>Abstract</summary>",
                    "",
                    abstract,
                    "",
                    f"</details>",
                ])

            lines.extend(["", "---", ""])
            idx += 1

    # Footer
    lines.extend([
        "",
        f"*Report generated by paper-search on {now}*",
    ])

    return "\n".join(lines)


def save_markdown(content: str, filename: str | None = None) -> str:
    """Save markdown content to the output directory. Returns the file path."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    if filename is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"papers_{timestamp}.md"

    filepath = os.path.join(OUTPUT_DIR, filename)
    with open(filepath, "w") as f:
        f.write(content)

    return filepath
