#!/usr/bin/env python3
"""Generate Top-K topic candidates for Obsidian paper notes using GPU sentence-transformers.

This does NOT modify any notes. It trains a conservative classifier from existing `research_directions`
labels and then ranks candidate papers for each label.

IMPORTANT (accuracy): uses ABSTRACT extracted from local_fulltext when available.
Fallback: title + One-sentence takeaway + Summary sections from the paper note.

Output:
  <vault>/dashboards/auto-topic-topk-candidates.md

"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple, Optional

import numpy as np
import yaml

LABELS = ["bias", "fairness", "summarization"]
FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.S)


def load_model(model_name: str):
    from sentence_transformers import SentenceTransformer
    import torch

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = SentenceTransformer(model_name, device=device)
    return model, device


def extract_frontmatter(text: str) -> Tuple[Dict[str, Any], str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    fm = yaml.safe_load(m.group(1)) or {}
    body = text[m.end() :]
    return fm, body


def normalize_rd(v: Any) -> List[str]:
    if v is None:
        return []
    if isinstance(v, str):
        return [v]
    if isinstance(v, list):
        return [x for x in v if isinstance(x, str)]
    return []


def extract_abstract_from_fulltext(fulltext_path: Path, max_chars: int = 3000) -> Optional[str]:
    """Extract abstract from markdown fulltext generated by the pipeline.

    Looks for a section marker like '## **Abstract**' (common in your cached fulltext files).
    """
    try:
        txt = fulltext_path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return None

    # Common patterns
    patterns = [
        r"^##\s+\*\*Abstract\*\*\s*$",
        r"^##\s+Abstract\s*$",
        r"^#\s+Abstract\s*$",
    ]

    start_idx = None
    for pat in patterns:
        m = re.search(pat, txt, flags=re.M)
        if m:
            start_idx = m.end()
            break
    if start_idx is None:
        return None

    # End at next heading
    m2 = re.search(r"^#{1,3}\s+", txt[start_idx:], flags=re.M)
    end_idx = start_idx + m2.start() if m2 else len(txt)

    abstract = txt[start_idx:end_idx].strip()
    # cleanup markdown artifacts
    abstract = re.sub(r"\n{3,}", "\n\n", abstract)
    abstract = re.sub(r"\s+", " ", abstract).strip()

    if not abstract:
        return None

    return abstract[:max_chars]


def build_paper_text_from_note(fm: Dict[str, Any], body: str) -> str:
    title = fm.get("title") or ""
    chunks = [f"Title: {title}".strip()]
    for header in ["# One-sentence takeaway", "# Summary", "# 中文简述"]:
        idx = body.find(header)
        if idx != -1:
            chunks.append(body[idx : idx + 2500])
    if len(chunks) == 1:
        chunks.append(body[:3000])
    text = "\n\n".join(chunks)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text


def build_paper_text(vault: Path, fm: Dict[str, Any], body: str) -> str:
    """Prefer ABSTRACT from local_fulltext for accurate semantic matching."""
    lf = fm.get("local_fulltext")
    if isinstance(lf, str) and lf:
        p = Path(lf)
        if p.exists():
            abs_txt = extract_abstract_from_fulltext(p)
            if abs_txt:
                title = fm.get("title") or ""
                return f"Title: {title}\n\nAbstract: {abs_txt}".strip()

    return build_paper_text_from_note(fm, body)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault", required=True)
    ap.add_argument("--model", default="allenai/specter2_base")
    ap.add_argument("--topk", type=int, default=200)
    args = ap.parse_args()

    vault = Path(args.vault)
    papers_dir = vault / "papers"
    if not papers_dir.exists():
        print(f"ERROR: papers dir not found: {papers_dir}", file=sys.stderr)
        sys.exit(2)

    files = sorted(papers_dir.glob("*.md"))
    rows = []
    for p in files:
        txt = p.read_text(encoding="utf-8")
        fm, body = extract_frontmatter(txt)
        if not fm:
            continue
        rd = normalize_rd(fm.get("research_directions"))
        y = [1 if lab in rd else 0 for lab in LABELS]
        text_for_embed = build_paper_text(vault, fm, body)
        rows.append({
            "path": p,
            "title": fm.get("title") or p.stem,
            "rd": rd,
            "y": y,
            "text": text_for_embed,
        })

    # training set
    X_train_text = [r["text"] for r in rows if any(r["y"])]
    y_train = np.array([r["y"] for r in rows if any(r["y"])], dtype=np.int32)
    if len(X_train_text) < 20:
        print(f"WARNING: only {len(X_train_text)} labeled papers found.")

    model, device = load_model(args.model)
    print(f"MODEL: {args.model} on {device}")

    X_train = model.encode(X_train_text, batch_size=32, show_progress_bar=True, convert_to_numpy=True, normalize_embeddings=True)

    from sklearn.linear_model import LogisticRegression

    clfs = []
    for j in range(len(LABELS)):
        clf = LogisticRegression(max_iter=2000, class_weight="balanced")
        clf.fit(X_train, y_train[:, j])
        clfs.append(clf)

    # embed all
    X_all = model.encode([r["text"] for r in rows], batch_size=32, show_progress_bar=True, convert_to_numpy=True, normalize_embeddings=True)
    probs = np.stack([clfs[j].predict_proba(X_all)[:, 1] for j in range(len(LABELS))], axis=1)

    out_lines = []
    out_lines.append(f"# Auto topic Top-K candidates\n")
    out_lines.append(f"Model: `{args.model}`\n")
    out_lines.append(f"Device: `{device}`\n")
    out_lines.append(f"Papers scanned: `{len(rows)}`\n")
    out_lines.append(f"Training labeled: `{len(X_train_text)}`\n")
    out_lines.append(f"TopK per label: `{args.topk}`\n")
    out_lines.append("Text source: `Abstract from local_fulltext when available` (fallback to note sections).\n")

    for j, lab in enumerate(LABELS):
        out_lines.append(f"\n---\n\n## {lab} — Top {args.topk} (excluding already-labeled)\n")
        idxs = [i for i, r in enumerate(rows) if lab not in r["rd"]]
        ranked = sorted(idxs, key=lambda i: float(probs[i, j]), reverse=True)[: args.topk]
        for rank, i in enumerate(ranked, start=1):
            r = rows[i]
            p = float(probs[i, j])
            # use one entry per 3 lines (avoid literal \\n mess)
            out_lines.append(f"{rank:>3}. `{r['path'].name}` (p={p:.3f})\n")
            out_lines.append(f"     - title: {r['title']}\n")
            out_lines.append(f"     - current research_directions: {r['rd']}\n")

    out_path = vault / "dashboards" / "auto-topic-topk-candidates.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("".join(out_lines), encoding="utf-8")
    print(f"OUT: {out_path}")


if __name__ == "__main__":
    main()
